---
- name: server configuration
  hosts: dev
  become: true
  tasks:
    - name: create user
      user:
        name: gold
        state: present       
    - name: create directory
      file:
        path: /home/azureuser/deply_dir
        state: directory
- name: file configuration
  hosts: all
  become: true
  tasks:
    - name: create file
      file:
        path: /home/azureuser/deply_dir/index.html
        state: touch
    - name: content for file
      copy:
        content: 'Ansible online class'
        dest: /home/azureuser/deply_dir/index.html  
