name: image-pushing-to-acr

on:
  push:
    branches:
      - master  # Change this if needed
env:
  ACR_REPO_NAME: "testing"  # Your container registry repo name
  TAG: "latest"                    # Or dynamically generate a tag
  CONTAINER_APP_NAME: "testing"  # Name of your Azure Container App
  RESOURCE_GROUP: "demo"
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/testing:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/testing:latest
      - name: Update Azure Container App to Use Latest ACR Image
        run: |
          IMAGE_URI="testingsd.azurecr.io/${{ env.ACR_REPO_NAME }}:${{ env.TAG }}"
    
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image $IMAGE_URI
